Q1: Have you come across Grid Search Cross Validation? Fit any two models covered in previous classes and optimize them using Grid search CV.

Ashly Thampi  
21BDA19

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score
from sklearn.model_selection import GridSearchCV
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        


In [3]:
df = pd.read_csv("/Users/ashlythampi/Downloads/SEM 2/ML Lab/winequality-red.csv")

In [4]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [5]:
df.head

<bound method NDFrame.head of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067  

In [6]:
df.corr

<bound method DataFrame.corr of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067

In [7]:
df.count()

fixed acidity           1599
volatile acidity        1599
citric acid             1599
residual sugar          1599
chlorides               1599
free sulfur dioxide     1599
total sulfur dioxide    1599
density                 1599
pH                      1599
sulphates               1599
alcohol                 1599
quality                 1599
dtype: int64

In [8]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [14]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [15]:
X = df.drop(['quality'], axis=1)

y = df['quality']

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)


In [17]:
X_train.shape, X_test.shape

((1071, 11), (528, 11))

In [18]:
X_train.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
dtype: object

In [19]:
X_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
548            12.4             0.350         0.49             2.6      0.079   
355             6.7             0.750         0.01             2.4      0.078   
1296            6.6             0.630         0.00             4.3      0.093   
209            11.0             0.300         0.58             2.1      0.054   
140             8.4             0.745         0.11             1.9      0.090   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
548                  27.0                  69.0  0.99940  3.12       0.75   
355                  17.0                  32.0  0.99550  3.55       0.61   
1296                 51.0                  77.5  0.99558  3.20       0.45   
209                   7.0                  19.0  0.99800  3.31       0.88   
140                  16.0                  63.0  0.99650  3.19       0.82   

      alcohol  
548      10.4  
355      12.8  
1296      9.5  
209      10.5  
140       9.6

In [20]:
X_test.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
803             7.7              0.56         0.08            2.50      0.114   
124             7.8              0.50         0.17            1.60      0.082   
350            10.7              0.67         0.22            2.70      0.107   
682             8.5              0.46         0.31            2.25      0.078   
1326            6.7              0.46         0.24            1.70      0.077   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
803                  14.0                  46.0   0.9971  3.24       0.66   
124                  21.0                 102.0   0.9960  3.39       0.48   
350                  17.0                  34.0   1.0004  3.28       0.98   
682                  32.0                  58.0   0.9980  3.33       0.54   
1326                 18.0                  34.0   0.9948  3.39       0.60   

      alcohol  
803       9.6  
124       9.5  
350       9.9  
682       9.8  
1326     10.6

In [21]:
from sklearn.tree import DecisionTreeClassifier


In [22]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=0)


# fit the model
clf_gini.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=3, random_state=0)

In [23]:
y_pred_gini = clf_gini.predict(X_test)


In [24]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy score with criterion gini index: 0.5208


### GridSearchCV

In [26]:
import warnings

warnings.filterwarnings('ignore')

rfc = DecisionTreeClassifier()

forest_params = [{'max_depth': list(range(1, 10)), 'max_features': list(range(0,14))}]

clf = GridSearchCV(rfc, forest_params, cv = 10, scoring='accuracy')

clf.fit(X_train, y_train)

print(clf.best_params_)

print(clf.best_score_)

{'max_depth': 8, 'max_features': 10}
0.6125129802699896


### Decision Tree Classifier

In [27]:
clf = DecisionTreeClassifier(random_state=0)

In [28]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [30]:
prediction = clf.predict(X_test)
confusion_matrix(y_test, prediction)

array([[  0,   1,   1,   0,   0,   0],
       [  0,   1,  10,   6,   2,   0],
       [  0,  11, 140,  56,   9,   1],
       [  0,   5,  49, 119,  37,   3],
       [  0,   2,   5,  25,  37,   1],
       [  0,   0,   0,   2,   3,   2]])

In [31]:
f1_score(y_test,prediction, average="micro")

0.5662878787878788

In [32]:
accuracy_score(y_test, prediction)

0.5662878787878788

### Random Forest Classifier

In [33]:
clf = RandomForestClassifier(n_estimators = 100, random_state = 18).fit(X_train, y_train)

In [34]:
prediction = clf.predict(X_test)

In [35]:
confusion_matrix(y_test, prediction)

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   9,  10,   0,   0],
       [  0,   0, 165,  50,   2,   0],
       [  0,   0,  46, 149,  18,   0],
       [  0,   0,   2,  40,  27,   1],
       [  0,   0,   0,   0,   6,   1]])

In [36]:
accuracy_score(y_test, prediction)

0.6477272727272727

In [37]:
f1_score(y_test,prediction, average="micro")

0.6477272727272727