# MACHINE LEARNING 1 ASSIGNMENT

### 1) Have you come across Grid search CV? Fit two model and perform grid search CV

I have heard about Grid search CV but not worked on this.

# IRIS data set classification using SVM and GridSearch

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import svm, datasets

### Let us import the Iris data set

In [2]:
data = pd.read_csv("C:/Users/User/Downloads/Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


### Split the data as Train and Test sets

In [4]:
from sklearn.model_selection import train_test_split
X = data.drop('Species', axis = 1)
y = data['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

### Let us train the model 

In [5]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train,y_train)

SVC()

### Let us do the predictions using the trained model

In [6]:
pred = svm.predict(X_test)

### Create confusion matrix

In [7]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

[[15  0  0]
 [ 0 13  0]
 [ 0  0 17]]


### Create classification report

In [8]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        17

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



In [9]:
svm.score(X_test,y_test)

1.0

###  Grid Search
Now we will tune the parameters, check for the improvement

Tuning parameters value for machine learning algorithms effectively improves the model performance ( Let us check in for our data)

### Import Gridsearch from Scikit Learn.

In [10]:
from sklearn.model_selection import GridSearchCV

### Create a dictionary called par_grid and fill out some parameters for C and Gamma

In [11]:
par_grid = {'C':[0.1,1,10,100], 'gamma':[1,0.1,0.01,0.001]}

Create a GridSearchCV object and fit it to the training data

Grid search is a model hyperparameter optimization technique.

In [12]:
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose=3)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV 1/5] END .................................C=0.1, gamma=1; total time=   0.0s
[CV 2/5] END .................................C=0.1, gamma=1; total time=   0.0s
[CV 3/5] END .................................C=0.1, gamma=1; total time=   0.0s
[CV 4/5] END .................................C=0.1, gamma=1; total time=   0.0s
[CV 5/5] END .................................C=0.1, gamma=1; total time=   0.0s
[CV 1/5] END ...............................C=0.1, gamma=0.1; total time=   0.0s
[CV 2/5] END ...............................C=0.1, gamma=0.1; total time=   0.0s
[CV 3/5] END ...............................C=0.1, gamma=0.1; total time=   0.0s
[CV 4/5] END ...............................C=0.1, gamma=0.1; total time=   0.0s
[CV 5/5] END ...............................C=0.1, gamma=0.1; total time=   0.0s
[CV 1/5] END ..............................C=0.1, gamma=0.01; total time=   0.0s
[CV 2/5] END ..............................C=0.1

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=3)

### Let us predict using the Grid model

In [13]:
pred_grid = grid.predict(X_test)

### confusion matrix

In [14]:
print(confusion_matrix(y_test, pred_grid))

[[15  0  0]
 [ 0 13  0]
 [ 0  0 17]]


### Let us print the report also

In [15]:
print(classification_report(y_test, pred_grid))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        17

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



The predictions looks the same in grid search cv too.
If any noise in the data, we need to tune the parameters, but it should not overfit the model.

# Model 2: Decision Classifier

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

Let us directly

In [46]:
iris = datasets.load_iris()

In [48]:
X, y = iris.data, iris.target

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [50]:
clf = DecisionTreeClassifier(random_state=0)

In [51]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [52]:
prediction = clf.predict(X_test)

In [53]:
confusion_matrix(y_test, prediction)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [54]:
accuracy_score(y_test, prediction)

0.96

In [55]:
f1_score(y_test,prediction, average="micro")

0.96

## Grid Search CV Implementation

In [56]:
grid = { 
    'splitter': ['best', 'random'],
    'max_features': ['sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8,9,10,12,14],
    'criterion' :['gini', 'entropy'],
    'random_state' : [18]
}

In [57]:
rf_cv = GridSearchCV(estimator=DecisionTreeClassifier(), param_grid=grid, cv= 5)
rf_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [4, 5, 6, 7, 8, 9, 10, 12, 14],
                         'max_features': ['sqrt', 'log2'], 'random_state': [18],
                         'splitter': ['best', 'random']})

In [58]:
rf_cv.best_params_

{'criterion': 'gini',
 'max_depth': 5,
 'max_features': 'sqrt',
 'random_state': 18,
 'splitter': 'random'}

In [59]:
clf = DecisionTreeClassifier(criterion='gini', max_depth=5, max_features='sqrt', splitter='random' , random_state=18)

In [60]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, max_features='sqrt', random_state=18,
                       splitter='random')

In [61]:
prediction = clf.predict(X_test)

In [62]:
confusion_matrix(y_test, prediction)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 15]], dtype=int64)

In [63]:
accuracy_score(y_test, prediction)

0.98

In [64]:
f1_score(y_test,prediction, average="micro")

0.98

In [65]:
clf = RandomForestClassifier(n_estimators = 100, random_state = 18).fit(X_train, y_train)

In [66]:
prediction = clf.predict(X_test)

In [67]:
confusion_matrix(y_test, prediction)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 15]], dtype=int64)

In [68]:
accuracy_score(y_test, prediction)

0.98

In [69]:
f1_score(y_test,prediction, average="micro")

0.98

Here we can see that parameters accuracy is same
Therefore the best parameters are given as {'criterion': 'gini', 'max_depth': 5, 'max_features': 'sqrt', 'random_state': 18, 'splitter': 'random'}
